services:
  redis:
    image: redis:7.4
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=StrongP@ssw0rd
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

